### ISSUE TITLE
On Safari card avatars' border is square

### ISSUE THREAD

**Issue by OleksandrHumeniuk** [fictadvisor/fictadvisor-web#238]
On Safari card avatars' border is square instead of circle. Seems to be an issue for all cards.

Example:
![image](https://user-images.githubusercontent.com/89925253/225569816-af240255-587d-47f8-85e5-fe02625b07c2.png)

**Comment by HJyup** [comment]
Works properly without solving.
<img width="1440" alt="Screenshot 2023-06-25 at 20 38 32" src="https://github.com/fictadvisor/fictadvisor-web/assets/89708817/99789c34-827f-462b-b4cb-f28a46166cac">
