### ISSUE TITLE
Fix size of container for teacher`s full name

### ISSUE THREAD

**Issue by Markusplay** [fictadvisor/fictadvisor-web#254]
On the */poll* every card`s full name that starts with upper case letters are cutted above and left side.
Possible fix: change paddings.

Examples:

1
 ![image](https://user-images.githubusercontent.com/102873980/225595631-34114a3f-14ec-48f6-937a-3f93b3632910.png)

2
 ![image](https://user-images.githubusercontent.com/102873980/225597374-c7f20fe6-f608-49fc-af98-109240498132.png)

3
![image](https://user-images.githubusercontent.com/102873980/225603709-e8408031-1b96-42f0-805a-b41d1bdda71d.png)

**Comment by Yevheniy2020** [comment]
chrome?

**Comment by Markusplay** [comment]
> chrome?

Chrome, desktop version
