### ISSUE TITLE
Refactor handing request errors

### ISSUE THREAD

**Issue by OleksandrHumeniuk** [fictadvisor/fictadvisor-web#308]
для кожної сторінки треба створити мапер з заготовленими помилками.

бек присилає імена помилок в відповіді, якщо запит упав

якщо в `catch` ми ловимо ерору і вона з аксіоса (для цього є функція перевірки) - треба дістати ім'я цієї ерори. прокинути це ім'я в мапер і дістати текст помилки.

потрібно написати generic інтерфейси для аксіоса, щоб грамотно працювала типізація, і переписати те як ми дістаємо помилки зараз. для типів помилок варто завести єнамки.

з приводу можливих помилок на конкретному запиті - контактувати з беком, вони або скажуть або відправлять на свагер

**Comment by Markusplay** [comment]
rejected
