### ISSUE TITLE
Rewrite PollPage using MUI

### ISSUE THREAD

**Issue by ria0308** [fictadvisor/fictadvisor-web#377]

**Comment by AnastasiaLytvyn** [comment]
poll page drafts should be saved in local storage full time and for each teacher separately 
now one draft used for all teachers and removed after opening any page not from breadcrumbs

**Comment by kotsiubkoserhiy** [comment]
1. The margin between "space for your comments" and "input" is too large.
![IMG_1834](https://github.com/fictadvisor/fictadvisor-web/assets/125184521/de7ee032-e131-4179-87e4-e9d22435fc14)
![IMG_1832](https://github.com/fictadvisor/fictadvisor-web/assets/125184521/93e64143-06ed-4e19-8f42-11712ea33f6c)

2. The margin between the question and the answer option is too small.
![IMG_1835](https://github.com/fictadvisor/fictadvisor-web/assets/125184521/4955f26f-7fdb-456f-8c4f-30680dc4a510)
![IMG_1833](https://github.com/fictadvisor/fictadvisor-web/assets/125184521/2975d1d4-84e0-4177-a58c-68454cccd8c5)

**Comment by kol-oss** [comment]
**Question header font size and its distance to the description are too small**

**Actual result:**
![image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/b96b421d-7a23-4a96-8980-49dddaa8e5a1)

**Expected result (figma):**
![image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/96d042e0-b532-43b5-babf-d0807ba8057f)

**Comment by kol-oss** [comment]
[MOBILE] "Go back" sign (<) on the top of the page placed incorrectly

Actual: "<" is very close to the text

![IMG_20230928_163507_994](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/e4853985-2641-4c98-9233-0e117c4a1a33)

Expected (figma): "<" is near the left end of the page
![IMG_20230928_163509_965](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/95a63b39-2081-4a3d-a938-51449b5a4bb6)

**Comment by kol-oss** [comment]
**Change "Ви"-form to "ти"-form**

![2023-09-28_21-26](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/4262877d-7805-4e4d-bb8d-b1a7abe5796c)
