### ISSUE TITLE
Add SSG/ISR to `/subjects/{subjectId}/teachers ` page

### ISSUE THREAD

**Issue by kujo205** [fictadvisor/fictadvisor-web#622]
FA is not displayed on google search page, while looking for a specific subject
![image](https://github.com/fictadvisor/fictadvisor-web/assets/86970828/59d7ba0f-1e39-4ff5-9208-7ec1f4e03a82)
To tackle this issue `nextJs 12` offers some tools.
One of which is using [Head](https://nextjs.org/docs/pages/api-reference/components/head) tag.
Your task is to implement ISR or SSG and put info about all the teachers in meta tags, thus browser crawlers will have the necessary information

**Comment by Markusplay** [comment]
UPD: Use SSR OR ISR, no SSG
