### ISSUE TITLE
Remove pages duplicates

### ISSUE THREAD

**Issue by Markusplay** [fictadvisor/fictadvisor-web#633]
Next pages have same structure, only text is changed, but they are different files. Unify them by creating template for these pages and use it to remove duplicates.
Password recovery flow:
1. link-expired
2. link-valid 
3. forgot-password-page
4. create-password-page (except business logic)

Confirmation pages:
1. RegistrationEmailConfirmationPage
2. PasswordResetEmailConfirmationPage
![image](https://github.com/fictadvisor/fictadvisor-web/assets/102873980/3c34b8f4-503f-456b-bd82-9948b9e44cc1)

**Comment by kujo205** [comment]
Залупа, а не таска, it violates SRP
