### ISSUE TITLE
FictAdvisor mobile app

### ISSUE THREAD

**Issue by mshabanov27** [fictadvisor/fictadvisor-web#642]
It would be much better, if there was a mobile app for FictAdvisor. Opening the website on phone browser every time is frustrating and takes too much time to access the reviews on teachers.

**Comment by just-hoshinon** [comment]
> It would be much better, if there was a mobile app for FictAdvisor. Opening the website on phone browser every time is frustrating and takes too much time to access the reviews on teachers.

You can join Dev Department and start creating mobile app with us <3

**Comment by mshabanov27** [comment]
@just-hoshinon I am not a mobile developer myself,  but wanted to suggest something, that can acquire new people to the department, where they can grow their skills in FA team if they wish to. Still, that's very kind of you Sviatoslav, thanks for the invitation!
