### ISSUE TITLE
[BUG] Error after clicking on the "Edit" button in the "Мої вибіркові" tab on the profile page for future semester

### ISSUE THREAD

**Issue by AnastasiaLytvyn** [fictadvisor/fictadvisor-web#679]
Error after clicking on the "Edit" button in the "Мої вибіркові" tab on the profile page for future semester

**Preconditions:** User is authorized

**Steps to reproduce**
1. Open main page
2. Click on the profile
3. Click on the "Мої вибіркові"
4. Click on the "Edit" button for 2 semester
5. Pay attention to the error page

**Actual result:** Application error: a client-side exception has occurred (see the browser console for more information).

https://github.com/fictadvisor/fictadvisor-web/assets/71929115/4b6fdeb8-65a3-4665-9770-99298e98e324

**Expected result:** Error notifications "Now you can not choose subject for this semester" or something like this :)

**Environment:**
-deploy: prod
-url: https://fictadvisor.com/account?tab=selective
-OS: Windows
-browser: Google Chrome 116.0.5845.141

**Comment by M-Rybalko** [comment]
Bug fixed, deployment: https://fictadvisor-ccp0xz76j-fict-advisor.vercel.app
