### ISSUE TITLE
Add 5 last missing endpoints in User API

### ISSUE THREAD

**Issue by kujo205** [fictadvisor/fictadvisor-web#700]
Our project has a folder, where all API related stuff is located, (`/lib`). Your task is to add 5 missing endpoints listed below
![image](https://github.com/fictadvisor/fictadvisor-web/assets/86970828/7632b493-6e36-4506-8424-d53b1f365442)

All of these could be found in the following [docs](https://apidev.fictadvisor.com/api)
Add these endpoints as methods on User class 
![image](https://github.com/fictadvisor/fictadvisor-web/assets/86970828/e5476517-1f04-424c-89a9-2eeaf4e62373)

Also u could read up on axios docs

**Comment by InfectusProg** [comment]
The task is already done by @Ak1yamaKiyoshi
