### ISSUE TITLE
[BUG] Output of incorrect information when entering an incorrect password when logging into the account.

### ISSUE THREAD

**Issue by AnastasiaLytvyn** [fictadvisor/fictadvisor-web#706]
Output of incorrect information when entering an incorrect password when logging into the account.

**Preconditions:** : the user entered a valid username but an incorrect password.

**Actual result:**  the cell with the user's name is highlighted in red

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/71929115/b05c4109-ae3c-4019-be7d-88c93aee2596)

**Expected result:** the cell with the user's name is not highlighted in red, because the
user has entered the correct name

**Environment:**
- deploy: prod;
- url: https://fictadvisor.com/login?~account ;
- OS: macOs;
- browser: Safari version 16.6 (17615.3.12.11.3, 17615).

**Comment by Markusplay** [comment]
UI/UX didn't cover this case.
