### ISSUE TITLE
[BUG] Both additional links get deleted on the Account page after clicking on delete button next to one of them

### ISSUE THREAD

**Issue by AnastasiaLytvyn** [fictadvisor/fictadvisor-web#711]
Both additional links get deleted on the Account page after clicking on delete button next to one of them

**Preconditions:**User is authorised.

**Steps to reproduce**
1. Open FICT Advisor (https://fictadvisor.com/).
2. Come to Account (https://fictadvisor.com/account?tab=general) page.
3. Add many social networks' contacts to your account. They must be from one platform (Telegram, YouTube etc.).
4. Click the delete button next to one of them.

**Actual result:** Both social networks' contacts got deleted.

https://github.com/fictadvisor/fictadvisor-web/assets/71929115/c3056766-424b-4cf0-94ea-ed477fe9f31f

**Expected result:** Only contact next to which delete button was clicked got deleted.

**Environment:**
• Deploy: Prod;
• URL: https://fictadvisor.com/account;
• OS: Android 13 TQ1.221114.001 / MIUI Global 14.0.2;
• Browser: Google Chrome 116.0.5845.163.

**Comment by Markusplay** [comment]
Firstly, it is backend problem
