### ISSUE TITLE
[BUG] No content validation in additional links on the Account page while creating new contact

### ISSUE THREAD

**Issue by AnastasiaLytvyn** [fictadvisor/fictadvisor-web#712]
No content validation in additional links on the Account page while creating new contact

**Preconditions:** User is authorised.

**Steps to reproduce**
1. Open FICT Advisor (https://fictadvisor.com/).
2. Come to Account (https://fictadvisor.com/account?tab=general) page.
3. Fill the fields in adding links block with incorrect information (wrong URL).

**Actual result:**  System accepts wrong links and gives possibility to redirect to another FA pages.

https://github.com/fictadvisor/fictadvisor-web/assets/71929115/7a198c92-3c2c-4527-8500-d66c61721620

**Expected result:** System doesn't allow to enter the unvalidated data (not links) in link field.

**Environment:**
• Deploy: Prod;
• URL: https://fictadvisor.com/account;
• OS: Android 13 TQ1.221114.001 / MIUI Global 14.0.2;
• Browser: Google Chrome 116.0.5845.163.

**Comment by Markusplay** [comment]
UI/UX and Backend didn't cover this case.

**Comment by Markusplay** [comment]
Backend didn't cover this case.

**Comment by Markusplay** [comment]
We have now endpoint with validation:
![image](https://github.com/fictadvisor/fictadvisor-web/assets/102873980/74c77820-8e8f-4b58-afd0-caecb978ad0b)
You need to show toast correct message if validation is not passed
