### ISSUE TITLE
[BUG] [MOBILE] Android: Empty space in the dropdown's header on the “Schedule” page

### ISSUE THREAD

**Issue by AnastasiaLytvyn** [fictadvisor/fictadvisor-web#734]
**Preconditions:** User choose more than 2 filters in the dropdown

SCREEN SIZE 339px-387px

**Actual result:** Empty space in the dropdown's header on the “Schedule” page

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/71929115/0307f528-8949-47e1-9299-c3b02fb99787)

**Expected result:** There is no empty space in the dropdown's header on the “Schedule” page,  remove empty space 

**Environment:**
-deploy: prod, dev
-url: https://fictadvisor.com/schedule?group=5ce5ad1c-c197-4fd9-ae7f-3c7f050c1742&week=3
-OS: Android 
-browser: Google Chrome

**Comment by igaryakqwe** [comment]
MUI uses this area to display other items in autocomplete, so if we delete this area, autocomplete won't open.
