### ISSUE TITLE
[BUG] Link directs to the outdated chat in 'Абітурієнт чат' card on the Main page after clicking on it

### ISSUE THREAD

**Issue by kol-oss** [fictadvisor/fictadvisor-web#747]
**Steps to reproduce**
1. Go to the Main page.
2. Click on 'Абітурієнт чат'.
3. Pay attention to the link and chat.

**Actual result:** Link directs to the outdated chat.

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/fa9c9d5a-1a78-4958-a266-6595dfbb6b8e)

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/ed4e5c33-524d-40cf-9747-e8c4a67bcc2a)

**Expected result:** Link directs to the actual chat (https://t.me/abit_fice).

**Environment:**
- deploy: Dev, Prod;
- url: https://fictadvisor.com/;
- OS: Android 13 TQ1.221114.001 / MIUI Global 14.0.2;
- browser: Google Chrome 116.0.5845.163.

**Comment by Markusplay** [comment]
closed as a Backend problem
