### ISSUE TITLE
[BUG] Account password can be unlimitedly long

### ISSUE THREAD

**Issue by guywhodiesfirst** [fictadvisor/fictadvisor-web#762]
Bug type: functional
Priority: mid

**Steps to reproduce**
1. Go to Account -> Security (or register a new account)
2. Enter new password with huge number of symbols

**Actual result:** you can change your password

**Expected result:** the error message is displayed that says "Password is too long"

**Environment:**
Deploy: dev/prod

URL: https://fictadvisor-kgwsufxhy-fict-advisor.vercel.app/account?tab=SECURITY or https://fictadvisor.com/account?tab=security

OS: Windows 10

Browser: Opera GX v. 100.0.4815.82

https://github.com/fictadvisor/fictadvisor-web/assets/144242408/099efb40-2a01-4aff-b224-442575478ddd

**Comment by Markusplay** [comment]
upd: max length of password: 32 symbols
