### ISSUE TITLE
[BUG] Typos in texts on email verification pages

### ISSUE THREAD

**Issue by kovaliovev** [fictadvisor/fictadvisor-web#788]
[FIRST TYPO]

**Steps to reproduce**

1. Go to the FA register page.
2. Register a new account.
3. Pay attention to the text.

**Actual result:** 
Texts are "Ми надіслали листа для підтвердження на адресу lytvynana@gmail.com", "Не отримав листа?".
**Expected result:**
Texts are "Ми надіслали лист для підтвердження на адресу lytvynana@gmail.com", "Не отримав лист?".

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/202012cc-314e-4e0b-b05b-985768f47309)

[SECOND TYPO]

**Steps to reproduce**

1. Go to the FA login page.
2. Click on the "Забув пароль?" link.
3. Enter any email.
4. Click on the "Надіслати лист" button.
5. Pay attention to the text.

**Actual result:** 
Texts are "Ми надіслали листа для зміни пароля на адресу lytvynana@gmail.com", "Не отримав листа?".
**Expected result:**
Texts are "Ми надіслали лист для зміни пароля на адресу lytvynana@gmail.com", "Не отримав лист?".

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/ca57bed7-fdf7-4665-a776-b530f943d1d0)

**Environment:**
- deploy: prod
- url: 
https://fictadvisor.com/register/email-verification?email=lytvynana@gmail.com ;
https://fictadvisor.com/password-recovery/email-verification?email=lytvynana@gmail.com
- OS: Windows 10
- browser: Google Chrome 116.0.5845.141

**Comment by AnastasiaLytvyn** [comment]
duplicate [788](https://github.com/fictadvisor/fictadvisor-web/issues/786)

**Comment by AnastasiaLytvyn** [comment]
duplicate [788](https://github.com/fictadvisor/fictadvisor-web/issues/786)
