### ISSUE TITLE
[BUG] The security tab icon is not matched the design on the "Безпека" tab

### ISSUE THREAD

**Issue by IK-24KudinaDiana** [fictadvisor/fictadvisor-web#871]
**Preconditions:**
Registered user;
**Steps to reproduce**
1. Open FICT Advisor https://dev.fictadvisor.com/.
2. Go to "Безпека" tab.
3. Go to "Група" tab.
4. Pay attention to the tab icon.

**Actual result:**

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/00b746f1-aa7f-43b4-bcd6-7ed9410516f2)

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/e839c3a0-a407-47b5-a18b-1eb127b2b7fd)

**Expected result:**

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/00c70223-4d6f-408d-bf6d-569340b92343)

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/5e2eef25-424c-4174-b61d-0ff777df011c)

**Environment:**
-deploy: prod, dev
-url: https://dev.fictadvisor.com/
-OS: Windows 11 Pro
-browser: Google Chrome 119.0.6045.124

**Comment by Markusplay** [comment]
The design has old version (v1) of icons from lib and should replace with new one(v2).
